#!/bin/bash
#
# bootstrap installs things.

set -e

info() {
  printf " [ \033[00;34m..\033[0m ] $1\n"
}

success() {
  printf "\r\033[2K [ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
  printf "\r\033[2K [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

install_chezmoi() {
  if [ ! -x "$(command -v chezmoi)" ]; then
    info "Installing chezmoi"
    brew install chezmoi
  fi
}

chezmoi_init() {
  info "Initializing chezmoi"
  chezmoi init --apply --interactive -S $HOME/.dotfiles
}

install_chezmoi
chezmoi_init

success "Bootstrap complete."
